version: "2"
services:
  mongo:
    image: mongo
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
  training:
    image: training
    build: .
    ports:
      - "3001:3000"
    entrypoint: "nodemon"
